stages:
  - build
  - deploy

build_frontend:
  stage: build
  image: node:18
  script:
    - cd frontend
    - npm ci
    - npm run build
  artifacts:
    paths:
      - frontend/build
  only:
    - main

deploy_to_ec2:
  stage: deploy
  image: ubuntu:22.04

  before_script:
    - apt update && apt install -y openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $13.206.102.133 >> ~/.ssh/known_hosts

  script:
    - scp -r frontend/build ubuntu@13.206.102.133:/home/ubuntu/build

    - ssh ubuntu@$EC2_HOST "
        set -e

        # Frontend
        sudo rm -rf /var/www/html/*
        sudo cp -r /home/ubuntu/build/* /var/www/html/

        # Backend
        cd ~/fullstack-app/backend

        if [ ! -d 'venv' ]; then
          python3 -m venv venv
        fi

        source venv/bin/activate
        pip install -r requirements.txt

        sudo systemctl restart gunicorn
        sudo systemctl reload nginx
      "

  only:
    - tags
